---
- hosts: all
  connection: ssh
  become: True
  gather_facts: False
  tasks:
   - name: Start and enable firewalld.
     service:
       name: firewalld
       state: started
       enabled: True
