---
- name: Create start.yaml for Proxmox VM
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate start.yaml
      copy:
        content: |
          vmid: "{{ proxmox_vm_id }}"
        dest: start.yaml
